<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">
<suite parallel="tests" name="Failed suite [Suite]" guice-stage="DEVELOPMENT" verbose="0">
  <test thread-count="5" parallel="tests" name="Error Validations Test(failed)" verbose="0">
    <groups>
      <run>
        <include name="ErrorHandling"/>
      </run>
    </groups>
    <classes>
      <class name="PragyaLearnings.Tests.ErrorValidations">
        <methods>
          <include name="LoginErrorValidation"/>
          <include name="TearDown"/>
          <include name="LaunchApplication"/>
        </methods>
      </class> <!-- PragyaLearnings.Tests.ErrorValidations -->
    </classes>
  </test> <!-- Error Validations Test(failed) -->
  <test thread-count="5" parallel="tests" name="Submit Order Test(failed)" verbose="0">
    <classes>
      <class name="PragyaLearnings.Tests.SubmitOrderTest2">
        <methods>
          <include name="OrderHistoryTest"/>
          <include name="SubmitOrder"/>
          <include name="TearDown"/>
          <include name="LaunchApplication"/>
        </methods>
      </class> <!-- PragyaLearnings.Tests.SubmitOrderTest2 -->
    </classes>
  </test> <!-- Submit Order Test(failed) -->
</suite> <!-- Failed suite [Suite] -->
